In [1]:
import numpy as np

In [8]:
a = np.arange(20)
b = np.reshape(a,(4,5))

In [11]:
c = np.random.random(20)

In [14]:
a < c

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False], dtype=bool)

In [12]:
counter = 0

def compare_matrices(a,b):
    
while counter < 100:
    
    counter += 1

array([ 0.98356116,  0.81044203,  0.01935748,  0.16030247,  0.43502957,
        0.90253333,  0.21620825,  0.87533763,  0.12186084,  0.77827973,
        0.23594549,  0.16797787,  0.24517751,  0.96356485,  0.52734147,
        0.44733945,  0.82106943,  0.415618  ,  0.98932018,  0.84127418])

In [45]:
x1 = np.arange(10).reshape((1,10))
x2 = np.random.random(10).reshape((1,10))
x_constant = np.ones((10)).reshape((1,10))

In [46]:
x1

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
x2

array([[ 0.63343299,  0.35754277,  0.14603803,  0.64369772,  0.10267552,
         0.26619253,  0.04127659,  0.90316836,  0.68136472,  0.70316448]])

In [48]:
x_constant

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [37]:
weights = np.random.random(3)

In [38]:
weights

array([ 0.33522509,  0.16415524,  0.22429675])

In [49]:
def my_dotproduct(a,b):
    """
    Parameters
    a : two-dimensional array
    b : two-dimensional array
    
    Output:
    c : the dotproduct
        return False if the input dimensions don't fit
    """
    a_dim1, a_dim2 = a.shape
    b_dim1, b_dim2 = b.shape
    
    if not a_dim2==b_dim1:
        print("Error: dimensions don't fit")
        return False
    
    c = np.zeros((a_dim1,b_dim2))
    
    for i in np.arange(a_dim1):
        for j in np.arange(a_dim2):
            for k in np.arange(b_dim2):
                c[i,k] += a[i,j]*b[j,k]

    return c

    
    
    

In [52]:
x1.shape

(1, 10)

In [53]:
x2.shape

(1, 10)

In [54]:
my_dotproduct(x1,x2)

Error: dimensions don't fit


False

In [55]:
my_dotproduct(x1,x2.transpose())

array([[ 22.67161284]])

In [57]:
c_costum_dotproduct = my_dotproduct(x1.transpose(),x2)

In [58]:
c_numpy = np.dot(x1.transpose(),x2)

In [59]:
c_costum_dotproduct == c_numpy

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [61]:
my_list = [np.arange(i*4) for i in range(3)]


In [62]:
my_list

[array([], dtype=int32), array([0, 1, 2, 3]), array([0, 1, 2, 3, 4, 5, 6, 7])]

In [64]:
my_list = [np.arange(i*4) for i in range(3)]

for array in my_list:
    print(len(array))

0
4
8


In [42]:
my_input = np.concatenate((x1,x2,x_constant),axis=0)

In [43]:
my_input.shape

(3, 10)

In [44]:
my_input

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
         5.        ,  6.        ,  7.        ,  8.        ,  9.        ],
       [ 0.16260253,  0.38579834,  0.16702123,  0.21280704,  0.21892354,
         0.08069898,  0.75230952,  0.42812996,  0.6033157 ,  0.33672689],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ]])

In [ ]:
output = np.dot()

In [3]:
np.reshape()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])